sudo: false
language: node_js
node_js:
  - 'stable'
  - 'lts/*'
#before_script:
#    - touch src/compiler.lisp
script: "npm run build && npm run test && npm run build && npm run release"

branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
